import type { Metadata } from "next";
import { Geist, Geist_Mono, Albert_Sans, Montserrat_Alternates } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const albertSans = Albert_Sans({
  variable: "--font-albert-sans",
  subsets: ["latin"],
  display: "swap",
});
const montserratAlternates = Montserrat_Alternates({
  variable: "--font-montserrat-alternates",
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
}); 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${albertSans.variable} ${montserratAlternates.variable} antialiased`}
      >
        <header className="fixed top-0 left-0 w-full bg-white shadow-md z-50">
          <div className="sm:px-8 mx-auto max-w-7xl">
          <nav className="flex items-center justify-between p-4">
            <div className="text-lg font-bold hidden sm:block">
              <Image
                src="/printforge-logo1.jpg"
                alt="PrintForge Logo"
                width={200}
                height={50}
                style={{ height: "auto" }}
              />
            </div>
            {/* mobile logo */}
            <div className="text-lg font-bold sm:hidden">
              <Image
                src="/printforge-logomobile.svg"
                alt="PrintForge Logo"
                width={40}
                height={20}
                style={{ height: "auto" }}
              />
            </div>
            <ul className="flex space-x-4">
              <li>
                <Link href="/" className="text-gray-600 hover:text-gray-900">
                  Home
                </Link>
              </li>
              <li>
                <Link href="/about" className="text-gray-600 hover:text-gray-900">
                  About
                </Link>
              </li>
              <li>
                <Link href="/3dmodels" className="text-gray-600 hover:text-gray-900">
                  3D Models
                </Link>
              </li>
            </ul>
          </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
